require("arpit.plugins-setup")
require("arpit.core.options")
require("arpit.core.keymaps")
require("arpit.core.colorscheme")
require("arpit.plugins.comment")
require("arpit.plugins.nvim-tree")
require("arpit.plugins.lualine")
